-include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=falcon-cluster
TOOL_FOLDER_NAME=falcon-cluster
WORKFLOW_VERSION=release_30
WORKFLOW_DESCRIPTION="<img src="https://github.com/bittremieux/falcon/blob/main/falcon_logo.png?raw=true" width="400"><br>\
The falcon spectrum clustering tool uses advanced algorithmic techniques for highly efficient processing of millions \
of MS/MS spectra. First, high-resolution spectra are binned and converted to low-dimensional vectors using feature hashing. \
Next, the spectrum vectors are used to construct nearest neighbor indexes for fast similarity searching. The nearest neighbor \
indexes are used to efficiently compute a sparse pairwise distance matrix without having to exhaustively compare all spectra to \
each other. Finally, density-based clustering is performed to group similar spectra into clusters.<br> \
<hr> \
<h4> Citation </h4>\
<a href='https://analyticalsciencejournals.onlinelibrary.wiley.com/doi/10.1002/rcm.9153'>Wout Bittremieux, Kris Laukens, William Stafford Noble, Pieter C. Dorrestein. Large-scale tandem mass spectrum clustering using fast nearest neighbor searching. Rapid Communications in Mass Spectrometry, e9153 (2021).</a>"