run_test:
	nextflow run workflow.nf -resume

run_test_multiple:
	nextflow run workflow.nf -resume --input_spectra='../data/test_data/*.mgf'

run_nina:
	nextflow run workflow.nf --input_spectra='../data/test_data/extracted_nina.mzML'
